php=" /home/xggong/home1/zhouy/php/bin/php ";
lammps=" /home/xggong/home1/zhouy/lammps-24Apr13/src/lmp_ubuntu ";
lammpspot=" /home/xggong/home1/zhouy/lammps-24Apr13/potentials"
mpirun=" /opt/intel/mpi/openmpi/1.6.3/icc.ifort/bin/mpirun  -np ";
python=' /home/xggong/home1/zhouy/soft/anaconda/bin/python '
phonopy= ' /home/xggong/home1/zhouy/soft/anaconda/bin/phonopy '
phonts=' /home/xggong/home1/zhouy/soft/PhonTS-1.1.4/src/PhonTS '
vasp=' /home/xggong/home1/zhouy/vasp '
vasppot='/home/xggong/home1/zhangyueyu/psudopotential/5.3_LDA'